# Generated by Django 3.0.6 on 2020-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
    ]
